---
- name: Enable system podman-restart-custom.service
  ansible.builtin.systemd:
    name: podman-restart-custom
    enabled: true
  become: true

- name: Enable global podman-restart-custom.service
  ansible.builtin.systemd:
    name: podman-restart-custom
    scope: global
    enabled: true
  become: true
